# Generated by Django 2.2.3 on 2019-11-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FocusPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Image path inside the media directory')),
                ('x', models.FloatField(default=0, help_text='From -1.0 (left) to 1.0 (right)', verbose_name='X')),
                ('y', models.FloatField(default=0, help_text='From -1.0 (bottom) to 1.0 (top)', verbose_name='Y')),
                ('width', models.PositiveIntegerField(default=0, editable=False, verbose_name='Width')),
                ('height', models.PositiveIntegerField(default=0, editable=False, verbose_name='Height')),
            ],
            options={
                'verbose_name': 'Focus Point',
                'verbose_name_plural': 'Focus Points',
                'ordering': ['path'],
            },
        ),
    ]
