# Generated by Django 4.2.13 on 2025-03-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_versions", "0002_auto_20191125_1545"),
    ]

    operations = [
        migrations.AddField(
            model_name="focuspoint",
            name="file_path_hash",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64
            ),
        ),
    ]
